### ISSUE TITLE
Create a TypeScript transformer to autogenerate properties and attributes for Custom Elements

### ISSUE THREAD

**Issue by matt-gadd** [dojo/webpack-contrib#43]
**Enhancement**
The current custom element target requires a decorator explicitly stating the properties and attributes for the element like so:

```ts
@customElement({
	tag: 'dojo-input',
	properties: [ 'theme', 'aria' ],
	attributes: [ 'placeholder' ],
	events: [ 'onBlur' ]
})
``` 
this can be quite laborious especially given users will have already stated the public api via a properties interface. 

the proposal would be to use the typescript checker to infer the properties and attributes from the widgets property interface and write the according decorator detail for them, for a user authoring the decorator they would only need to provide a tag name like so:

```ts
@customElement({ tag: 'dojo-input' })
```

we'd also gain the other advantage that we'd be able to actually know the types of the properties so we can perform transformations for attribute types other than a string

**Comment by matt-gadd** [comment]
Thinking this through a little further. I think for the end user we should make this decorator-less. They can specify the tagname as a build arg or via the .dojorc so no need for them to even touch the widget source code.

Some further information for deciding what goes in what custom element section for MVP also:

* Any widget property that contains a `string` type can be added as an `attribute`
* Any widget property that is a function with no return type can be added as an `event`
* Anything that does not fit the above goes into a `property`

**Comment by grayrest** [comment]
I have an initial pass at transforming the decorator up on a branch on my fork. The [typescript docs](https://github.com/Microsoft/TypeScript/wiki/Using-the-Compiler-API#using-the-type-checker) have an example of doing the type inspection part and more or less do what we want. We need to recurse into the class' top level children instead of just dealing with the class itself but that's a couple line change.

The holdup is that we want a transformer while the type checking code from the examples works on the whole program after the code transformations and type checking have been completed. I don't think this is a problem since all the examples on that page work off the top level compiler API and wanting to do type-related transforms is a fairly obvious use case but I haven't managed to track down what I need to do to make it happen.

**Comment by rorticus** [comment]
Have a couple of PRs in for this. I'll list them out as they are in separate packages and are dependent on each other.

- https://github.com/dojo/webpack-contrib/pull/133 adds a transformer for automatically creating the custom element descriptors for widgets. This has no dependencies! (that haven't already been merged)
- https://github.com/dojo/cli-build-widget/pull/53 adds support to cli-build-widget to apply the transformer. This depends on the transformer being merged into webpack-contrib.
- https://github.com/dojo/widgets/pull/697 removes custom element descriptors from existing widgets and updates the build process to build each widget serially, rather than including them all in a single build. This technically has no dependencies, but unless the last two PRs are merged custom element descriptors will not work anymore.

As an overview of how this works now: You specify custom element widgets in your `.dojorc` (same as now). If the default export of those files is a class and extends some class that takes a generic, it is assumed to be a widget class. A `MyWidget.prototype.__customElementDescriptor` line is generated to set custom element information for that widget. Attributes are identified as those that are strings or can take strings as any of their values. For example if a type is `title: DNode`, `title` will be an attribute as `DNode` contains a string type. This works for enums as well. If a property is a function type, it is assumed to be an event, and everything else gets put in properties.  A widget author can override attributes/properties/events/tagname by using the old `@customElement` decorator.
